config/routes.rb
Rails.application.routes.draw do
  resources :profiles, :roles

  root to: 'home#index'

  resources :books do
  	member do
  		put :issue
      put :return
  	end
  end

  devise_for :users, controllers: { registrations: "users/registrations" }
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
  # before_create :build_profile
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource
  # before_action :set_current_user_profile, only: [:edit, :update, :destroy]
  before_action :set_profile, only: [:show]

  # before_action :set_profile, only: [:show, :edit, :update, :destroy]
  # before_action :set_profile, only: [:show]

  # GET /profiles
  # GET /profiles.json
  def index
    @user = User.find(current_user.id)
    @profile = Profile.find_by_user_id(@user.id)
    @profiles = Profile.all
    @books = Book.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @books = Book.all
    @user = User.find(current_user.id)
    Rails.logger.info "@user is =======> #{@user.inspect}"
    @own_profile = @profile.user_id == current_user.id ? true : false
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @user = User.find(current_user.id)
    @own_profile = @profile.user_id == current_user.id ? true : false
    puts "------------------#{@profile.inspect}--------------------"
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :address, :contact)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="container">
  <div class='col-sm-8' style='float:none; background'>
    <%= form_for @profile do |f| %>
      <% if @profile.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

          <ul>
          <% @profile.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label 'First Name' %>
        <%= f.text_field :first_name, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label 'Last Name' %>
        <%= f.text_field :last_name, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label 'Address' %>
        <%= f.text_field :address, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label 'Contact' %>
        <%= f.text_field :contact, :class => 'form-control' %>
      </div>

        <%= f.submit 'Submit',:class => 'btn btn-primary'  %>
      
    <% end %>

  </div>
</div>

app/views/profiles/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to('Home', root_path) %> 
        </li>
        <li>
          <%= link_to('My Profile', profile_path(@profile)) %>
        </li>
        <li>
          <%= link_to('Books', books_path(@books)) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>      
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/profiles/edit.html.erb
<%= render 'navbar' %>

<h3>Editing Profile</h3>

<%= render 'form' %>

app/views/profiles/index.html.erb
<%= render 'navbar' %>

<div class="container">
  <h2>Users Table</h2>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>User ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Address</th>
        <th>Contact</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @profiles.each do |profile| %>
        <tr>
          <td><%= profile.user_id %></td>
          <td><%= profile.first_name %></td>
          <td><%= profile.last_name %></td>
          <td><%= profile.address %></td>
          <td><%= profile.contact %></td>
          <td><%= link_to 'Edit', edit_profile_path(profile),:class => 'btn btn-primary btn-block' %></td>
          <td><%= link_to 'Delete', profile,:class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
 

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<%= render 'navbar' %>
  
<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li>
          <%= link_to 'Edit Profile', edit_profile_path(@profile), :class => 'btn btn-primary btn-block' %>
        </li>
        <li>  
          <% if can? :crud, Profile %>
            <%= link_to "Users List", profiles_path,:class => 'btn btn-primary btn-block' %>
          <% end %>
          <% if can? :crud, Book %>
            <%= link_to "Add New Book", new_book_path, :class => 'btn btn-primary btn-block' %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="col-sm-8 text-left">
      <h1>Welcome <%= @profile.first_name %></h1>
      <hr>
      <div class="panel panel-primary">
        <div class="panel-heading">Profile Details</div>
        <div class="panel-body">
          <h4>First name:
          <%= @profile.first_name %></h4>
          <h4>Last name:
          <%= @profile.last_name %></h4>
          <h4>Address:
          <%= @profile.address %></h4>
          <h4>Contact:
          <%= @profile.contact %></h4>
        </div>
      </div>
    </div>
  </div>
</div>