config/routes.rb
Rails.application.routes.draw do
  resources :profiles, :roles

  root to: 'home#index'

  resources :books do
  	member do
  		put :issue
      put :return
  	end
  end

  devise_for :users, controllers: { registrations: "users/registrations" }
  
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	# belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :issue, :return]

	def index
    @profile = Profile.find_by_user_id(current_user.id)
    @user = User.find(current_user.id)
    @books = Book.all
  end

  def new
    @profile = Profile.find_by_user_id(current_user.id)
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @profile = Profile.find_by_user_id(current_user.id)
    @user = User.find(current_user.id)
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to(@book)
    else
      render :action => :new
    end
  end

  def edit
    @profile = Profile.find_by_user_id(current_user.id)
    @user = User.find(current_user.id)
  end

  def update
    @book.update(book_params)
    if @book.update(book_params)
      redirect_to(@book)
    else
      render :action => :edit
    end
  end

  def issue
    @book.user_id = current_user.id
    @book.issued = true
    @book.date_of_issue = Time.now
    @book.save
    redirect_to books_path
  end

  def return
    @book.user_id = nil
    @book.issued = false
    @book.return_date = Time.now
    @book.save
    redirect_to books_path
  end

  def destroy
    @book.destroy
    if @book.destroy
      redirect_to books_path
    else
      render :action => :show
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :rating, :user_id, :isbn, :avatar)
    end
end

app/helpers/books_helper.rb
module BooksHelper

	def book_issued?(book)
    book.issued == true
  end

  def display_return_link?(book)
    book_issued?(book) && (book.user_id == current_user.id)
  end

  def display_issue_or_return_link(book)
    if display_return_link?(book)
      link_to 'Return This Book', return_book_path(book),:method => :put, data: {confirm: 'Are you sure'},:class => 'btn btn-block btn-success'
    elsif book_issued?(book)
      link_to 'Book already issued', '#',:class => 'btn btn-block btn-success disabled'
    else
      link_to 'Issue This Book', issue_book_path(book),:method => :put, data: {confirm: 'Are you sure'},:class => 'btn btn-block btn-success'
    end
  end

  def display_crud_link(book)
    str = ""
    if can? :crud, Book
      str += "#{link_to 'Edit Book Details', edit_book_path(book), :method => :get, :class => 'btn btn-block btn-primary'}"
      str += "#{link_to 'Delete This Book', book, :class => 'btn btn-block btn-danger', :method => :delete, data: { confirm: 'Are you sure?' } }"
    end
    str
  end

end

app/views/books/_form.html.erb
<div class="container">
  <div class='col-sm-8' style='float:none; background'>
    <%= form_for @book do |f| %>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label 'Title' %>
        <%= f.text_field :title, :class => 'form-control' %>
      </div>

      <div class="forn-group">
        <%= f.label 'Author' %>
        <%= f.text_field :author, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label 'Rating' %>
        <%= f.number_field :rating, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label 'Isbn' %>
        <%= f.text_field :isbn, :class => 'form-control' %>
      </div>

      <div class="control-label">
        <%= f.label :avatar %>
        <%= f.file_field :avatar %>
      </div>

     
      <%= f.submit 'Update', :class=> 'btn btn-primary'%>
      
    <% end %>
  </div>
</div>

app/views/books/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to('Home', root_path) %> 
        </li>
        <li>
          <%= link_to('My Profile', profile_path(@profile)) %>
        </li>
        <li>
          <%= link_to('Books', books_path(@books)) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>      
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/books/edit.html.erb
<%= render 'navbar' %>

<%= render 'form' %>

app/views/books/index.html.erb
<%= render 'navbar' %>

<h1>Listing Books</h1>

<div class="container">
  <% @books.each do |book| %>
    <div class="col-sm-3">
      <div class="row">
        <%= link_to(image_tag(book.avatar.url(:medium)),book_path(book)) %>
      </div>
      <br>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<%= render 'navbar' %>

<h2>Add New Book </h2>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<%= render 'navbar' %>

<div class="container-fluid text-center">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li>
          <%= display_issue_or_return_link(@book) %>
       </li>
        <li>
          <%= display_crud_link(@book).html_safe %>
        </li>
      </ul>
    </div>
    <div class="col-sm-8 text-left">
      <%= image_tag @book.avatar.url(:medium) %>
      <h4><strong>Title:</strong><%= @book.title %></h4>
      <h4><strong>Author:</strong><%= @book.author %></h4>
      <h4><strong>Rating:</strong><%= @book.rating %></h4>
      <h4><strong>Isbn:</strong><%= @book.isbn %></h4>
    </div>
  </row>
</div>